---
- hosts: all
  sudo: true
	tasks:
	  - name: update apt cache

	    apt:update_cache=yes

	  - name: install nodejs
	  
	    apt: name=nodejs state=present	
	  
	  - name: install socketio
	    
	    npm: name=socket.io
		
